### [회원가입] 정상 요청
# @no-cookie-jar
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "Abcd1234!",
  "username": "슬몽몽2" ,
  "role": "USER"
}

###

### [로그인] 정상 요청 + 쿠키 저장
# @no-cookie-jar
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "Abcd1234!"
}
> {%
  // 쿠키 자동 저장
  client.global.set("JSESSIONID", response.headers.get("Set-Cookie").split(";")[0].split("=")[1]);
  client.log("JSESSIONID : " + client.global.get("JSESSIONID"));
%}
