
### 리뷰 저장 요청 (자동으로 쿠키 붙음)
POST http://localhost:8080/api/reviews
Content-Type: multipart/form-data; boundary=boundary
Cookie: JSESSIONID={{JSESSIONID}}

--boundary
Content-Disposition: form-data; name="requestDto"
Content-Type: application/json


{
  "storeId": 1,
  "content": "리뷰 내용",
  "rating": 5
}

--boundary
Content-Disposition: form-data; name="files"; filename="join.png"
Content-Type: image/png

< C:/Users/dnjs7/OneDrive/사진/스크린샷/join.png
--boundary
Content-Disposition: form-data; name="files"; filename="ee.png"
Content-Type: image/png

< C:/Users/dnjs7/OneDrive/사진/스크린샷/ee.png
--boundary--
### 가게 별 리뷰 조회
GET http://localhost:8080/api/reviews?storeId=1
Cookie: JSESSIONID=YOUR_SESSION_ID

###

### 별점 기준 리뷰 조회
GET http://localhost:8080/api/reviews?rating=5
Cookie: JSESSIONID=YOUR_SESSION_ID

###

### 로그인 유저 리뷰 조회
GET http://localhost:8080/api/reviews/user
Cookie: JSESSIONID=YOUR_SESSION_ID

###

### 리뷰 삭제
DELETE http://localhost:8080/api/reviews/1
Cookie: JSESSIONID=YOUR_SESSION_ID

###

### 리뷰 수정
PATCH http://localhost:8080/api/reviews/1
Content-Type: multipart/form-data
Cookie: JSESSIONID=YOUR_SESSION_ID

--boundary
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "content": "수정된 리뷰입니다!",
  "rating": 4
}
--boundary
Content-Disposition: form-data; name="files"; filename="ww.png"
Content-Type: image/png

< C:/Users/dnjs7/OneDrive/사진/스크린샷/ww.png
--boundary--
