POST http://localhost/api/reviews
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "storeId": 1,
  "userId": 1,
  "content": "리뷰 내용",
  "rating": 5
}
--MyBoundary
Content-Disposition: form-data; name="file"; filename="ee.png"
Content-Type: image/png

< C:/Users/dnjs7/OneDrive/사진/스크린샷/ee.png
Content-Disposition: form-data; name="file"; filename="ww.png"
Content-Type: image/png

< C:/Users/dnjs7/OneDrive/사진/스크린샷/ww.png
--MyBoundary--
### 리뷰 삭제 테스트
DELETE http://localhost/api/reviews/1
